### PR TITLE
Feature/RB-29|Create-login-page

### PR DESCRIPTION
**Pull request by chien-b1812825**
I hope for your feedback!

### CODE REVIEW

**Comment by chien-b1812825** [comment]
I mean, I need your review and merge this PR to finish my homework. Please help me.

**Comment by maksJopek** [comment]
I'm very sorry for the delay, I didn't saw this PR. Please, make another one, but to develop.

**Comment by maksJopek** [comment]
I have two requests for you, could you change bootstrap version to 5 and change colorscheme to gruvbox, we had meeting on Thursday and choosed it. If you don't have time, that's fine, we will make another issue to change it.

**Comment by chien-b1812825** [comment]
My English is not good. I think I can't understand if you say on the meet.
And one more thing, I have to report to my teacher on Monday. So I think we
should make another issue to change it.
Thank you !

Vào CN, 14 thg 11, 2021 vào lúc 18:38 maksJopek ***@***.***>
đã viết:

**Pull request closed without merging**
